# Generated by Django 3.2.9 on 2023-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
