# Generated by Django 3.2.9 on 2023-07-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_userorder_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
    ]
