# Generated by Django 3.2.9 on 2023-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_userorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='items',
        ),
        migrations.AddField(
            model_name='userorder',
            name='items',
            field=models.TextField(null=True),
        ),
    ]
