# Generated by Django 3.2.9 on 2023-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20230721_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='items',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
