# Generated by Django 3.2.9 on 2023-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_userorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='deliveryAddress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='items',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
